### PR TITLE
Add patches for th-desugar and singletons

### PR DESCRIPTION
**Pull request by RyanGlScott**

### CODE REVIEW

**Comment by hvr** [comment]
merged & head.hackage updated; Thanks!

**Comment by christiaanb** [comment]
This patch fails for me on GHC 8.2.2, which according to the readme should work. 

I have a `cabal.project` file with:

```
repository head.hackage
  url: http://head.hackage.haskell.org/
  secure: True
  root-keys: 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740
             2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb
             8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e
  key-threshold: 3
```

And calling `cabal new-build` in a project that depends on `singletons` results in:

```
Building library for singletons-2.3.1..
[ 1 of 56] Compiling Data.Singletons  ( src/Data/Singletons.hs, dist/build/Data/Singletons.o )
[ 2 of 56] Compiling Data.Singletons.Decide ( src/Data/Singletons/Decide.hs, dist/build/Data/Singletons/Decide.o )
[ 3 of 56] Compiling Data.Singletons.SuppressUnusedWarnings ( src/Data/Singletons/SuppressUnusedWarnings.hs, dist/build/Data/Singletons/SuppressUnusedWarnings.o )
[ 4 of 56] Compiling Data.Singletons.Syntax ( src/Data/Singletons/Syntax.hs, dist/build/Data/Singletons/Syntax.o )

src/Data/Singletons/Syntax.hs:102:10: error:
    Not in scope: type constructor or class ‘Semigroup’
    |
102 | instance Semigroup ULetDecEnv where
    |          ^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
Oh dear, this is my fault for just taking the patch straight from the `singletons` git repo (which simultaneously dropped compatibility with GHC 8.2). I think all you'd need to do to correct the patch is add an explicit import for `Data.Semigroup`. I'll get around to submitting a working patch later today (unless you want to do it sooner).

As a side note, it would be really nifty if `head.hackage`'s Travis CI job could actually build all of the packages that have patches checked in (or at the very least, the latest versions of each package). But perhaps that's too large of an ask.

**Comment by hvr** [comment]
@RyanGlScott I've just been looking at the patch; there's more to it: the `Monoid` instances are missing `mappend = (<>)` for pre-SMP compat.

**Comment by christiaanb** [comment]
Perhaps we should just remove this patch completely? there's `singletons-2.4.*` which only works with base-4.11 i.e. ghc-8.4

**Comment by RyanGlScott** [comment]
I mean, it does serve some utility for those libraries that have a `singletons < 2.4` upper version bound, so perhaps it would be hasty to remove it entirely.

**Comment by hvr** [comment]
@RyanGlScott did this actually compile w/ GHC 8.4.x? I'm running into

```
src/Data/Singletons/Util.hs:82:17: error:
    • The constructor ‘DNormalC’ should have 2 arguments, but has been given 1
    • In the pattern: DNormalC stys
      In an equation for ‘tysOfConFields’:
          tysOfConFields (DNormalC stys) = map snd stys
```

**Comment by RyanGlScott** [comment]
Are you using `th-desugar-1.7`? That was a breaking API change between 1.7 and 1.8.

**Comment by hvr** [comment]
Right, sorry my bad, had a typo in `--allow-newer=base,template-haskell`

**Comment by hvr** [comment]
I've hopefully fixed it up in dae272caf11f92adac5f872117b9a3b40a51d2b8 although there were still a few worrying

```
src/Data/Singletons/Util.hs:359:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘qAddCorePlugin’
    • In the instance declaration for ‘Quasi (QWithAux m q)’
```

warnings for GHC 8.4

**Comment by RyanGlScott** [comment]
Eh, I wouldn't worry about those warnings. If those are an issue for you, then you're probably using `singletons-2.4.1` by now ;)

**Comment by christiaanb** [comment]
@hvr Everything's working now, thanks
